### ISSUE TITLE
Import source elements from ePO

### ISSUE THREAD

**Issue by cristianvasquez** [OP-TED/epo-conceptual-model#1]
Bring the following contents from https://github.com/OP-TED/ePO:

- ePO_CM.eap

For the branches:

- release/4.1.0
- develop

**Comment by cristianvasquez** [comment]
@andreea-pasare, the initial commit is done, please check if it is as expected

**Comment by andreea-pasare** [comment]
Checked main, develop and release/4.1.0 branches and it looks ok. Thank you!
